---
name: Catalina
surname: Cañizares
position: "PhD Candidate"
address: "Florida International University"
email: "ccani007@fiu.edu"
twitter: CatalinaCaniza1
github: ccani007
orcid: 0000-0002-6854-5205
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
docname: CV
output: 
  vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
library(tidyverse)
library(here)
library(readr)
library(scholar)
```

# Education

```{r education}

tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "PhD in Social Welfare", "Current", "Florida International University", "Miami, United States",
  "Master in Clinical and Health Psychology", "2014", "Universidad de los Andes", "Bogotá, Colombia",
  "Pyschology", "2012", "Universidad de los Andes", "Bogotá, Colombia"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Research

```{r research_tribble,include=FALSE}
research <- tribble(
  ~title, ~unit, ~startYear, ~endMonth, ~endYear, ~where, ~ professor, ~detail,
  
  "Research Coordinator", "Robert Stempel College of Public Health and Social Work", 2022, "Present", NA, "Florida International University", 
  "Roberto Lucchini, M.D", "World Trade Center Health Study in Florida.
  \\begin{itemize}
     \\item Build the strategy to collect data and grant application support 
  \\end{itemize}", 
  
  "Research Assistant as an Independent Contractor", "School of Social Work", 2022, 
  "Present", NA, "Boston College", 
  "Maria Piñeros-Leaño, Ph.D.", "Mothers and Children of All Nations Defying the Odds.  
  \\begin{itemize}
     \\item Analysis of qualitative data
  \\end{itemize}", 
  
  "Research Assistant", "Department of psychology", 2012, "Present", NA, "Universidad de los Andes", "Yvonne Gómez, Ph.D.", "Depression and genetics.  
  \\begin{itemize}
     \\item Review and select literature, collect and analyze data, evaluate and write proposals for publication. 
  \\end{itemize}",
  
  "Research Assistant", "Department of psychology", 2018, "January", 2019, "Universidad de los Andes", "Leonidas Castro Ph.D.",
  "Adaptation and Validation of the Unified Protocol for victims of armed conflict in Colombia.
  \\begin{itemize}
     \\item Implement the Unified Protocol with victims of armed conflict in Colombia
   \\end{itemize}"
  
  )
```

```{r research}

research %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F)

```

# Teaching Experience

```{r teaching_tribble, include=FALSE }
teaching <-  tribble(
  ~title, ~unit, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
  "Co-Teacher", "R Computing for Health Sciences", "June", 2023, "August", 2023, "Florida International University", "Introduction to Supervised Machine Learning",   
  "Teacher Assistant", "R Medicine 2023", "June", 2023, "June", 2023, "Virtual Conference", "R Medicine 101: Introduction to Clinical Data Analysis with R",   
   "Instructor", "The Research Centers in Minority Institutions (RCMI) Consortium", 
  "February", 2023, "May", 2023, "Morehouse School of Medicine", "A 10-week national series to the R Programming language, using a modified version of the R for Reproducible Scientific Analysis Data Carpentry curriculum", 
  
  "Teacher Assistant", "Institute for Data Science and Computing", "February", 2023, "February", 2023, "Miami University", "Facilitated educational sessions on Git, Shell, and R using the Data Carpentry curriculum", 
  
   "Teacher Assistant", "Biostatistics",  "January", 2023, "April", 2023, "Florida International University", "Avanced R for posgraduate students",
  
  "Teacher Assistant", "Biostatistics",  "June", 2022, "August", 2022, "Florida International University", "Avanced R for posgraduate students", 
  
  "Graduate Teaching Assistantship", "Spanish Center", "January", 2013, "December", 2013, "Universidad de los Andes", 
  "Tutored undergraduate students in Spanish writing skills. 
  \\begin{itemize}
        \\item Developed and implemented activities and rubrics to evaluate skills in Spanish writing.
        \\item Assisted the course Fundamentals of Psychology (spring, 2013 and fall, 2013).
    \\end{itemize}",
  
  "Undergraduate Teaching Assistantship", "Department of Psychology", "January", 2010, "May", 2010, "Universidad de los Andes", 
  "Assisted the course Neuroscience 1 (Spring, 2010)")

```

```{r teaching}
teaching %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F)
```

# Publications

```{r}
bibliography_entries("bib/Publications.bib") %>% 
  arrange(desc(issued))
```

# Software development

```{r}
bibliography_entries("bib/Software.bib") 
```

# Conference presentations

```{r}
bibliography_entries("bib/Presentations.bib") 
```

# Workshops

```{r}
bibliography_entries("bib/Workshops.bib") 
```


# Work in Progress

```{r}
bibliography_entries("bib/In_progress.bib") 
```


# Skills

```{=tex}
\begin{cvskills}  
\cvskill    {Software}    {Microsoft Office, SPSS, ATLAS.ti, Nvivo, Dedoose}      
\cvskill    {Programming Languages}    {R, Python}  
\cvskill    {Reproducible Report}    {Quarto, Markdown/Rmarkdown, R shiny apps, Jupyter Notebook}  
\cvskill    {DevOps}    {Git, GitHub}      
\cvskill    {Web development}    {Wordpress, GitHub Pages, Netlify}  \cvskill    {Languages}    {Spanish, English}
\end{cvskills}
```



# Honors

```{r honors_tribble, include=FALSE }
honors <-  tribble(
  ~area, ~accomplishment, ~year, ~detail, ~where,
  
  "Honorable Mention: NIDA International Poster Session", "Society for Prevention Research", 2023, "Honorable Mention for Poster Hopelessness in Youth: A Supervised Machine Learning Classification Approach to Identify Risk Factors. Prize: SPR Membership for 2024", "Washington, D.C",
  
  "The C.V. Starr Scholarship", "Robert Stempel College of Public Health and Social Work", 2023, "Scholarship for Latin America and The Caribbean  doctoral students with an award of up to $27,941", "Miami, FL",
  
   "The Stempel Travel Award", "Robert Stempel College of Public Health and Social Work", 2023, "Award to graduate students in FIU Stempel College to attend conferences of up to $750", "Miami, FL",
  
  "Fulbright", "Scholarship Fulbright-Minciencias", 2020, "Scholarship for Doctoral studies in the United States of America for $330.000.000 COP","Bogotá",
  
  "Spanish Center Award", "Scholarship for posgraduate studies", 2013, "Awarded for academic excellence and proficient knowledge in Spanish writing skills", "Universidad de los Andes" ) 

```

```{r honors}
honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

# Professional Membership

```{r membership}
professional_membership <- tribble(
  ~title, ~member, ~startYear, ~endYear, 
  "Society for Social Work and Research", "Member", 2021, "Present", 
  "Society for Prevention Research", "Member", 2023, "Present", 
  "International Association for Social Work With Groups", "Member", 2023, "Present", 
  "American Psychological Association", "Member", 2022, "2023"
)
```


```{r membership_table}
professional_membership%>%
  detailed_entries(
    with = title,
    what = member,
    when = glue::glue("{startYear} - {endYear}",.na = ""),
    .protect = F
  )
```

# Professional Experience

```{r professional_experience_tribble, include=FALSE}
professional_experience <- tribble(
  ~title, ~unit, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
  "Academic Coordinator", "School of Education", "October", 2017, "July", 2020, "Universidad de los Andes", 
  "Arrangement of academic matters like schedules, lectures, classes and summer school for undergraduate, postgraduate and PhD programs of the School of Education. 
  \\begin{itemize}
        \\item Assess the quality of academic processes.
        \\item Support students throughout their programs and warrant their graduation.
        \\item Systematize information and use it to improve academic processes.
    \\end{itemize}",
  
  "Clinical Psychologist", "Office of student affairs", "March", 2017, "October", 2017, "Universidad de los Andes", 
  "Provided psychological attention for undergraduate and graduate students. \\begin{itemize}
        \\item Designed psycho-educational workshops for students.
        \\item Mediated in disciplinary cases.
        \\item Supported the development of the protocol to report cases of sexual abuse and harassment (MAAD).
    \\end{itemize}",
  
  "Clinical Manager of the Center of Psychology, Casa-Espinosa", "Department of Psychology", "February", 2014, "March", 2017, "Universidad de los Andes", 
  "Supervised students practicum of the Master in Clinical and Health Psychology. 
  \\begin{itemize}
        \\item Guided the development of intervention guidelines for the center of psychological attention.
        \\item Implemented technological features to gather information from patients to be used in further investigation.  
        \\item Represented the center at the Colombian Network of Psychological University Centers Red ISUAP 
    \\end{itemize}"
  )

```

```{r professional_experience}
professional_experience %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} - {endMonth} {endYear}",.na = ""),
    where = where, .protect = F
  )
```
